service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 120 # optional, in seconds, default is 6

functions:
  todo:
    handler: handler.todo
    events:
      # Invoke Lambda function every hour
      - schedule: rate(1 hour)
      